language: python
python:
  - "2.7"
  - "3.7"
  - "3.8"
  - "3.9"
# command to install dependencies
install:
  - pip install .
# command to run tests
script: pytest
# only notify when status changes from success to failure
notifications:
  email:
    recipients:
      - code@ramiro.org
    on_failure: change
